## **EXPERIMENT #2 - Numerical Python**
### Name: Tomenio, Julian Bernice Kristoffer
### Section: 2ECE-A

#### Date Submitted: September 03, 2024

## NORMALIZATION PROBLEM

In [19]:
import numpy as np

X = np.random.random((5, 5))

def normalization(X):
    normal = (X - np.mean(X))/np.std(X)
    return normal

np.save('X_normalized.npy', normalization(X))
X

array([[0.52843882, 0.75325354, 0.96009682, 0.98428048, 0.60447951],
       [0.92988188, 0.61821911, 0.86951539, 0.47320375, 0.24022032],
       [0.95634001, 0.58893093, 0.70959025, 0.17255738, 0.95459732],
       [0.94785431, 0.4306304 , 0.73551543, 0.18989875, 0.25166253],
       [0.18227892, 0.35731506, 0.0056964 , 0.76548745, 0.94078455]])

In [21]:
norm_matrix = np.load("X_normalized.npy")
rounded_std = round(np.std(X),4)

print("The Mean for overall matrix:",np.mean((X)),"\n\nThe Standard Deviation of the matrix:",rounded_std,"\n\nAs a result the normalized matrix:\n\n",norm_matrix)

The Mean for overall matrix: 0.606029173426927 

The Standard Deviation of the matrix: 0.3012 

As a result the normalized matrix:

 [[-0.25762841  0.48883888  1.17563444  1.25593304 -0.00514544]
 [ 1.07530976  0.04047507  0.87487086 -0.44102911 -1.21461953]
 [ 1.16316046 -0.05677243  0.34386075 -1.43928531  1.15737408]
 [ 1.13498481 -0.58238826  0.42994186 -1.38170561 -1.17662723]
 [-1.40700623 -0.82582205 -1.99332497  0.52945994  1.11151062]]


## DIVISIBLE BY 3 PROBLEM

In [13]:
import numpy as np

A = np.arange(1,101,1)**2

A = A.reshape(10,10)

def div3(array):
    array = array[array%3 == 0]
    return array

np.save("div_by_3.npy",div3(A))

print("The Squares of the First 100 Positive Integers:\n\n",A)

The Squares of the First 100 Positive Integers:

 [[    1     4     9    16    25    36    49    64    81   100]
 [  121   144   169   196   225   256   289   324   361   400]
 [  441   484   529   576   625   676   729   784   841   900]
 [  961  1024  1089  1156  1225  1296  1369  1444  1521  1600]
 [ 1681  1764  1849  1936  2025  2116  2209  2304  2401  2500]
 [ 2601  2704  2809  2916  3025  3136  3249  3364  3481  3600]
 [ 3721  3844  3969  4096  4225  4356  4489  4624  4761  4900]
 [ 5041  5184  5329  5476  5625  5776  5929  6084  6241  6400]
 [ 6561  6724  6889  7056  7225  7396  7569  7744  7921  8100]
 [ 8281  8464  8649  8836  9025  9216  9409  9604  9801 10000]]


In [24]:
div3_matrix = np.load("div_by_3.npy")

print("The Elements that are divisible by 3:\n\n",div3_matrix)

The Elements that are divisible by 3:

 [   9   36   81  144  225  324  441  576  729  900 1089 1296 1521 1764
 2025 2304 2601 2916 3249 3600 3969 4356 4761 5184 5625 6084 6561 7056
 7569 8100 8649 9216 9801]
