## **EXPERIMENT #2 - Numerical Python**
### Name: Tomenio, Julian Bernice Kristoffer
### Section: 2ECE-A

#### Date Submitted: September 03, 2024

## NORMALIZATION PROBLEM

In [27]:
import numpy as np

# Generate a 5x5 matrix of random numbers between 0 and 1
X = np.random.random((5, 5))

def normalization(X):
    # Normalize the input matrix X by subtracting the mean and dividing by the standard deviation
    normal = (X - np.mean(X)) / np.std(X)
    return normal

# Save the normalized matrix to a .npy file
np.save('X_normalized.npy', normalization(X))
# Display the original random matrix
X

array([[0.75097115, 0.81930539, 0.11138862, 0.36224365, 0.95673834],
       [0.54255315, 0.22039845, 0.2377595 , 0.50339603, 0.50350824],
       [0.40092824, 0.16132697, 0.36620104, 0.0555138 , 0.37519739],
       [0.67457404, 0.21624152, 0.21913281, 0.09547913, 0.40648126],
       [0.56750882, 0.74044198, 0.18574831, 0.25411406, 0.66945415]])

In [34]:
# Load the normalized matrix from a .npy file
norm_matrix = np.load("X_normalized.npy")

# Calculate the standard deviation of the original matrix X and round it to 4 decimal places
rounded_std = round(np.std(X), 4)

# Print the mean of the original matrix X, the rounded standard deviation, and the normalized matrix
print("The Mean for overall matrix:", np.mean((X)), 
      "\n\nThe Standard Deviation of the matrix:", rounded_std, 
      "\n\nAs a result the normalized matrix:\n\n", norm_matrix)

The Mean for overall matrix: 0.5977267575482348 

The Standard Deviation of the matrix: 0.2428 

As a result the normalized matrix:

 [[-0.27248227 -1.08363376  0.70733167 -1.1835929   0.57584264]
 [-0.12957629 -1.47070704 -0.13207213 -2.10228427  0.17534214]
 [ 1.62294029  1.53989416  0.25587752 -0.08083422 -1.32601629]
 [ 1.14075782  1.22914094  1.35905401 -0.93240798  0.67016415]
 [ 0.29682851  0.05341436 -1.33431634 -0.01049273  0.43182799]]


## DIVISIBLE BY 3 PROBLEM

In [36]:
import numpy as np

# Create an array of squares of the first 100 positive integers
A = np.arange(1,101,1)**2

# Reshape the array into a 10x10 matrix
A = A.reshape(10,10)

def div3(array):
    # Filter the array to include only elements that are divisible by 3
    array = array[array%3 == 0]
    return array

# Save the filtered array (elements divisible by 3) to a .npy file
np.save("div_by_3.npy",div3(A))

# Print the 10x10 matrix of squares
print("The Squares of the First 100 Positive Integers:\n\n",A)

The Squares of the First 100 Positive Integers:

 [[    1     4     9    16    25    36    49    64    81   100]
 [  121   144   169   196   225   256   289   324   361   400]
 [  441   484   529   576   625   676   729   784   841   900]
 [  961  1024  1089  1156  1225  1296  1369  1444  1521  1600]
 [ 1681  1764  1849  1936  2025  2116  2209  2304  2401  2500]
 [ 2601  2704  2809  2916  3025  3136  3249  3364  3481  3600]
 [ 3721  3844  3969  4096  4225  4356  4489  4624  4761  4900]
 [ 5041  5184  5329  5476  5625  5776  5929  6084  6241  6400]
 [ 6561  6724  6889  7056  7225  7396  7569  7744  7921  8100]
 [ 8281  8464  8649  8836  9025  9216  9409  9604  9801 10000]]


In [38]:
# Load the NumPy array from the specified file "div_by_3.npy"
div3_matrix = np.load("div_by_3.npy")

# Print a message indicating the elements that are divisible by 3
# followed by the contents of the div3_matrix
print("The Elements that are divisible by 3:\n\n", div3_matrix)

The Elements that are divisible by 3:

 [   9   36   81  144  225  324  441  576  729  900 1089 1296 1521 1764
 2025 2304 2601 2916 3249 3600 3969 4356 4761 5184 5625 6084 6561 7056
 7569 8100 8649 9216 9801]
