## **EXPERIMENT #2 - Numerical Python**

### NORMALIZATION PROBLEM
Normalization is one of the most basic pre-processing techniques in data analytics and involves centering an  scaling process. Centering means subtracting the data from the mean and scaling means dividing with its standard deviation.

In [35]:
import numpy as np

# Generate a 5x5 matrix of random numbers between 0 and 1
X = np.random.random((5, 5))

def normalization(X):
    # Normalize the input matrix X by subtracting the mean and dividing by the standard deviation
    normal = (X - np.mean(X)) / np.std(X)
    return normal

# Save the normalized matrix to a .npy file
np.save('X_normalized.npy', normalization(X))
# Display the original randomize matrix
X

array([[0.23810476, 0.20321035, 0.53301235, 0.07738752, 0.1613657 ],
       [0.81691226, 0.68111821, 0.89589023, 0.06014926, 0.08412218],
       [0.67186619, 0.52965778, 0.30414743, 0.95053888, 0.99336636],
       [0.22536166, 0.50544416, 0.27078855, 0.43516085, 0.08333202],
       [0.86901697, 0.98321674, 0.75009413, 0.90865784, 0.78107218]])

In [37]:
# Load the normalized matrix from a .npy file
norm_matrix = np.load("X_normalized.npy")

# Calculate the standard deviation of the original matrix X and round it to 4 decimal places
rounded_std = round(np.std(X), 4)

# Print the mean of the original matrix X, the rounded standard deviation, and the normalized matrix
print("The Mean for overall matrix:", np.mean((X)), 
      "\n\nThe Standard Deviation of the matrix:", rounded_std, 
      "\n\nAs a result the normalized matrix:\n\n", norm_matrix)

The Mean for overall matrix: 0.520519783657639 

The Standard Deviation of the matrix: 0.3222 

As a result the normalized matrix:

 [[-0.87638873 -0.98467288  0.03876687 -1.37512558 -1.11452497]
 [ 0.91976351  0.49836815  1.16484749 -1.42861927 -1.35422663]
 [ 0.46965734  0.02835698 -0.6714455   1.33443288  1.46733489]
 [-0.91593305 -0.04678259 -0.77496457 -0.26488538 -1.35667865]
 [ 1.08145455  1.43583864  0.71241386  1.20446788  0.80854475]]


### DIVISIBLE BY 3 PROBLEM
Create the following 10 x 10 array which are the squares of the first 100 positive integers. From this array, determine all the elements that are divisible only by 3.

In [31]:
import numpy as np

# Create an array of squares of the first 100 positive integers
A = np.arange(1,101,1)**2

# Reshape the array into a 10x10 matrix
A = A.reshape(10,10)

def div3(array):
    # Filter the array to include only elements that are divisible by 3
    array = array[array%3 == 0]
    return array

# Save the filtered array (elements divisible by 3) to a .npy file
np.save("div_by_3.npy",div3(A))

# Display the 10x10 matrix of squares
print("The Squares of the First 100 Positive Integers:\n\n",A)

The Squares of the First 100 Positive Integers:

 [[    1     4     9    16    25    36    49    64    81   100]
 [  121   144   169   196   225   256   289   324   361   400]
 [  441   484   529   576   625   676   729   784   841   900]
 [  961  1024  1089  1156  1225  1296  1369  1444  1521  1600]
 [ 1681  1764  1849  1936  2025  2116  2209  2304  2401  2500]
 [ 2601  2704  2809  2916  3025  3136  3249  3364  3481  3600]
 [ 3721  3844  3969  4096  4225  4356  4489  4624  4761  4900]
 [ 5041  5184  5329  5476  5625  5776  5929  6084  6241  6400]
 [ 6561  6724  6889  7056  7225  7396  7569  7744  7921  8100]
 [ 8281  8464  8649  8836  9025  9216  9409  9604  9801 10000]]


In [48]:
# Load the NumPy array from the specified file "div_by_3.npy"
div3_matrix = np.load("div_by_3.npy")

# Print a message indicating the elements that are divisible by 3 using the contents of the div3_matrix
print("The Elements that are divisible by 3:\n\n", div3_matrix)

The Elements that are divisible by 3:

 [   9   36   81  144  225  324  441  576  729  900 1089 1296 1521 1764
 2025 2304 2601 2916 3249 3600 3969 4356 4761 5184 5625 6084 6561 7056
 7569 8100 8649 9216 9801]
